package com.aztlansoft.koua.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import com.aztlansoft.koua.model.KouaMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession
{

  private final DaoConfig kouaMessageDaoConfig;

  private final KouaMessageDao kouaMessageDao;

  public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
          daoConfigMap)
  {
    super(db);

    kouaMessageDaoConfig = daoConfigMap.get(KouaMessageDao.class).clone();
    kouaMessageDaoConfig.initIdentityScope(type);

    kouaMessageDao = new KouaMessageDao(kouaMessageDaoConfig, this);

    registerDao(KouaMessage.class, kouaMessageDao);
  }

  public void clear()
  {
    kouaMessageDaoConfig.getIdentityScope().clear();
  }

  public KouaMessageDao getKouaMessageDao()
  {
    return kouaMessageDao;
  }

}
